root: .

dirs:
    cache: .cache/huggingface
    hub_cache: ${dirs.cache}/hub
    datasets_cache: ${dirs.cache}/datasets
    modules_cache: ${dirs.cache}/modules
    runs: runs
    logs: logs
    saves: save/models
    train: train
    test: test

subdirs:
  wandb: ${dirs.logs}/wandb
  train_checkpoints: ${dirs.train}/checkpoints
  test_outputs: ${dirs.test}/models

create:
    - ${dirs.cache}
    - ${dirs.hub_cache}
    - ${dirs.datasets_cache}
    - ${dirs.modules_cache}
    - ${dirs.runs}
    - ${dirs.logs}
    - ${dirs.saves}
    - ${dirs.train}
    - ${dirs.test}
    - ${subdirs.wandb}
    - ${subdirs.train_checkpoints}
    - ${subdirs.test_outputs}
