root: .

dirs:
    runs: runs
    logs: logs
    saves: save/models
    train: train
    test: test

subdirs:
  wandb: ${dirs.logs}/wandb
  train_checkpoints: ${dirs.train}/checkpoints
  test_outputs: ${dirs.test}/models

create:
    - ${dirs.runs}
    - ${dirs.logs}
    - ${dirs.saves}
    - ${dirs.train}
    - ${dirs.test}
    - ${subdirs.wandb}
    - ${subdirs.train_checkpoints}
    - ${subdirs.test_outputs}
