root:  ${oc.env:MODEL_ROOT,.}

dirs:
    logs: logs
    saves: save/models
    train: train
    test: test
    template: templates

subdirs:
  wandb: ${dirs.logs}/wandb
  train_checkpoints: ${dirs.train}/checkpoints
  test_outputs: ${dirs.test}/models

create:
    - ${dirs.custom}
    - ${dirs.saves}
    - ${dirs.train}
    - ${dirs.test}
    - ${subdirs.wandb}
    - ${subdirs.train_checkpoints}
    - ${subdirs.test_outputs}
